# Generated by Django 4.2.7 on 2023-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_active',
            new_name='active_employee',
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
