# Generated by Django 4.2.7 on 2023-11-28 23:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_rename_is_active_contact_active_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
