# Generated by Django 4.2.7 on 2023-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_contact_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('isoc', 'ISOC')], max_length=50, null=True),
        ),
    ]
